version: '3'
services:
  dependencies:
    build: .
    image: base 
  db:
    container_name: postgres_wb_db
    image: postgres:16.0
    restart: always
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wb_db
    healthcheck:
      test: "pg_isready --username=postgres && psql --username=postgres --list"
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
  redis:
    image: redis
    ports: 
      - "6379:6379"
    healthcheck:
        test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
        interval: 1s
        timeout: 3s
        retries: 5
  order: 
    container_name: order_service
    build: 
      context: ./cmd/order/
      dockerfile: Dockerfile
    volumes:
      - ./logs:/app/logs
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  nats:
    image: nats-streaming:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8222/healthz || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 5

